DROP TABLE IF EXISTS tg_user, operator, service, driver_license_service,
    bank_card_service CASCADE;
DROP TYPE IF EXISTS section_id;

CREATE TABLE tg_user (
        tg_id int8 PRIMARY KEY,
        tg_username varchar(255) NOT NULL
);

CREATE TYPE section_id AS ENUM (
    'PAYMENT_CONTROL',
    'BANK_CARD',
    'DRIVER_LICENSE'
    );

CREATE TABLE operator (
    operator_id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tg_id int8 REFERENCES tg_user(tg_id) ON DELETE CASCADE,
    name varchar(255),
    operation_section section_id NOT NULL,
    UNIQUE (tg_id, operation_section)
);

CREATE TABLE service (
    service_id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_tg_id int8 REFERENCES tg_user(tg_id) ON DELETE CASCADE,
    customer_name varchar(255),
    request_date date,
    payment_photo varchar(255),
    is_paid bool NOT NULL DEFAULT FALSE,
    service_executor int REFERENCES operator(operator_id) ON DELETE CASCADE
);

CREATE TABLE driver_license_service (
    service_id int REFERENCES service(service_id) ON DELETE CASCADE,
    blood_type varchar(255),
    height_cm int,
    category_a bool NOT NULL DEFAULT FALSE,
    category_b bool NOT NULL DEFAULT FALSE,
    international bool NOT NULL DEFAULT FALSE,
    is_form_complete bool NOT NULL DEFAULT FALSE,
    passport varchar(255),
    is_passport_complete bool NOT NULL DEFAULT FALSE,
    e_visa varchar(255),
    is_visa_complete bool NOT NULL DEFAULT FALSE
);

CREATE TABLE bank_card_service (
    service_id int REFERENCES service(service_id) ON DELETE CASCADE,
    full_name varchar(255),
    mother_name varchar(255),
    marital_status varchar(255),
    last_education varchar(255),
    indonesian_phone_number varchar(255),
    overseas_phone_number varchar(255),
    indonesian_address varchar(255),
    overseas_address varchar(255),
    address_email varchar(255),
    occupation varchar(255),
    company_name varchar(255),
    business_type_company varchar(255),
    address_company varchar(255),
    is_form_complete bool NOT NULL DEFAULT FALSE,
    passport varchar(255),
    is_passport_complete bool NOT NULL DEFAULT FALSE
);
